### ISSUE TITLE
How to assign selector of same class

### ISSUE THREAD

**Issue by aftab464** [xbsoftware/enjoyhint#98]
Like i have multiple Modals in which i have dropdowns of same class for example;

i want apply enjoy hint on "#ChapterAllocationModal .ClassDropdown"

and i have SubjectAllocationModal in which there is same class dropdown, i want apply enjoy hint on "#SubjectAllocationModal .ClassDropdown".

```
var enjoyhint_script_steps = [
  {
    'click  #ChapterAllocationModal  .ClassDropdown' : 'Click the "New" button to start creating your project'
  }  
];
```
is this a correct way ?

**Comment by zapper59** [comment]
That will select elements matching both the class and id.  You're going to want to use the greater than hierarchy operator. https://www.tutorialrepublic.com/jquery-reference/jquery-selectors.php

**Comment by stejas995** [comment]
var enjoyhint_script_steps = [{
            //selector: "button[name='buttoncreate']",
            'click .buttoncreate': 'This button allows you to switch between the search results',
            // event_type: "next",
            // description: "Button to create apps",
            showSkip: false
        }
    ];
    ERROR TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')
    at enjoyhint.min.js:1:1977
    at o.<computed> (wm-libs.min.js:110:448)
    at e.invokeTask (wm-libs.min.js:13:7900)
    at Object.onInvokeTask (wm-libs.min.js:570:191530)
    at e.invokeTask (wm-libs.min.js:13:7821)
    at t.runTask (wm-libs.min.js:13:2959)
    at t.invokeTask (wm-libs.min.js:13:9056)
    at o.useG.invoke (wm-libs.min.js:13:8947)
    at n.args.<computed> (wm-libs.min.js:110:146)
    could you please help me with this

**Comment by tsemashkoXB** [comment]
Hi @affiahmedkhan , thanks for reporting this, and sorry for the long silence!

Nested / descendant selectors (e.g. `#ChapterAllocationModal .ClassDropdown`) are supported in the new version — the full selector is preserved correctly now.

Please try the latest release and let us know if anything still looks off.
